services:
  app:
    build: .
    container_name: notelock_app
    ports:
      - "8000:80"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: notelock_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
